# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/52c3b46b-1c73-4e78-82eb-55fc23f34dbd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-cd67bc6d-c6f8-454e-8c4d-0ef3be21de9f".device = "/dev/disk/by-uuid/cd67bc6d-c6f8-454e-8c4d-0ef3be21de9f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F0EA-B0D4";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/40070e34-167e-40c7-bbce-8cdaf9acc067";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
